//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Test.WebPrint {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZHRWS_ZCPS", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZHRWS_ZCPS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Zhr00FmZcpsdyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZHRWS_ZCPS() {
            this.Url = global::Test.Properties.Settings.Default.Test_WebPrint_ZHRWS_ZCPS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Zhr00FmZcpsdyCompletedEventHandler Zhr00FmZcpsdyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZHRWS_ZCPS:Zhr00FmZcpsdyRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zhr00FmZcpsdyResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zhr00FmZcpsdyResponse Zhr00FmZcpsdy([System.Xml.Serialization.XmlElementAttribute("Zhr00FmZcpsdy", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zhr00FmZcpsdy Zhr00FmZcpsdy1) {
            object[] results = this.Invoke("Zhr00FmZcpsdy", new object[] {
                        Zhr00FmZcpsdy1});
            return ((Zhr00FmZcpsdyResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Zhr00FmZcpsdyAsync(Zhr00FmZcpsdy Zhr00FmZcpsdy1) {
            this.Zhr00FmZcpsdyAsync(Zhr00FmZcpsdy1, null);
        }
        
        /// <remarks/>
        public void Zhr00FmZcpsdyAsync(Zhr00FmZcpsdy Zhr00FmZcpsdy1, object userState) {
            if ((this.Zhr00FmZcpsdyOperationCompleted == null)) {
                this.Zhr00FmZcpsdyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZhr00FmZcpsdyOperationCompleted);
            }
            this.InvokeAsync("Zhr00FmZcpsdy", new object[] {
                        Zhr00FmZcpsdy1}, this.Zhr00FmZcpsdyOperationCompleted, userState);
        }
        
        private void OnZhr00FmZcpsdyOperationCompleted(object arg) {
            if ((this.Zhr00FmZcpsdyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zhr00FmZcpsdyCompleted(this, new Zhr00FmZcpsdyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmZcpsdy {
        
        private string icnumField;
        
        private string zhrzjlxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Icnum {
            get {
                return this.icnumField;
            }
            set {
                this.icnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrzjlx {
            get {
                return this.zhrzjlxField;
            }
            set {
                this.zhrzjlxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmZcpsdyResponse {
        
        private string gesctxtField;
        
        private string icnumField;
        
        private string mesField;
        
        private string nachnField;
        
        private string orgtxField;
        
        private string pernrField;
        
        private string zhrbzField;
        
        private string zhrpzhField;
        
        private string zhrzcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gesctxt {
            get {
                return this.gesctxtField;
            }
            set {
                this.gesctxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Icnum {
            get {
                return this.icnumField;
            }
            set {
                this.icnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nachn {
            get {
                return this.nachnField;
            }
            set {
                this.nachnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Orgtx {
            get {
                return this.orgtxField;
            }
            set {
                this.orgtxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrbz {
            get {
                return this.zhrbzField;
            }
            set {
                this.zhrbzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrpzh {
            get {
                return this.zhrpzhField;
            }
            set {
                this.zhrpzhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrzc {
            get {
                return this.zhrzcField;
            }
            set {
                this.zhrzcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Zhr00FmZcpsdyCompletedEventHandler(object sender, Zhr00FmZcpsdyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zhr00FmZcpsdyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zhr00FmZcpsdyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zhr00FmZcpsdyResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zhr00FmZcpsdyResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591