//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipedf.Web {


    public partial class PageObject_BGT_B_BUDGET_PROJ_ADJUST_Resource_Param
    {
        
        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// command 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComControlBar command;
        
        /// <summary>
        /// txtQueryNAME 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtQueryNAME;
        
        /// <summary>
        /// ddlQueryITEM_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComBaseBox ddlQueryITEM_ID;
        
        /// <summary>
        /// ddlQueryIS_GOV_PROC 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComDropDownList ddlQueryIS_GOV_PROC;
        
        /// <summary>
        /// txtQueryCODE 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtQueryCODE;
        
        /// <summary>
        /// txtQueryBUDEGT_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtQueryBUDEGT_MONEY;
        
        /// <summary>
        /// revtxtQueryBUDEGT_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtQueryBUDEGT_MONEY;
        
        /// <summary>
        /// txtQueryEXECUTED_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtQueryEXECUTED_MONEY;
        
        /// <summary>
        /// revtxtQueryEXECUTED_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtQueryEXECUTED_MONEY;
        
        /// <summary>
        /// txtQueryAPPLY_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtQueryAPPLY_MONEY;
        
        /// <summary>
        /// revtxtQueryAPPLY_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtQueryAPPLY_MONEY;
        
        /// <summary>
        /// txtQueryAPPLIED_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtQueryAPPLIED_MONEY;
        
        /// <summary>
        /// revtxtQueryAPPLIED_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtQueryAPPLIED_MONEY;
        
        /// <summary>
        /// ddlQuerySOURCE_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComDropDownList ddlQuerySOURCE_ID;
    }
}
