//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XH_Print.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zhr00_cw1/800/zcw1/zcw1")]
        public string XH_Print_QcSalary_ZCW1 {
            get {
                return ((string)(this["XH_Print_QcSalary_ZCW1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zhr00_cw2/800/zhr00_cw2/zhr00_cw2")]
        public string XH_Print_Srzm_ZHR00_CW2 {
            get {
                return ((string)(this["XH_Print_Srzm_ZHR00_CW2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zhr00_cw3/800/zhr00_cw3/zhr00_cw3")]
        public string XH_Print_MonthSalary_ZHR00_CW3 {
            get {
                return ((string)(this["XH_Print_MonthSalary_ZHR00_CW3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zhr00_cw4/800/zhr00_cw4/zhr00_cw4")]
        public string XH_Print_SearchMonthSalary_ZHR00_CW4 {
            get {
                return ((string)(this["XH_Print_SearchMonthSalary_ZHR00_CW4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zhr00_cw5/800/zhr00_cw5/zhr00_cw5")]
        public string XH_Print_JxSearch_ZHR00_CW5 {
            get {
                return ((string)(this["XH_Print_JxSearch_ZHR00_CW5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zfi02_ws_jfdd/800/zfi02_ws_jfdd/zfi02_ws_j" +
            "fdd")]
        public string XH_Print_accountFundSearch_ZFI02_WS_JFDD {
            get {
                return ((string)(this["XH_Print_accountFundSearch_ZFI02_WS_JFDD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p01app1:8001/sap/bc/srt/rfc/sap/zfi02_ws_jfmx/800/zfi02_ws_jfmx/zfi02_ws_j" +
            "fmx")]
        public string XH_Print_detailFund_ZFI02_WS_JFMX {
            get {
                return ((string)(this["XH_Print_detailFund_ZFI02_WS_JFMX"]));
            }
        }
    }
}
