//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipedf.App.HIS_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.trasen.com.cn/", ConfigurationName="HIS_Service.TrasenWSSoap")]
    public interface TrasenWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trasen.com.cn/ExeWebService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExeWebService(string PostType, string PostString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trasen.com.cn/GetXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetXml(string PostType, string PostString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrasenWSSoapChannel : Ipedf.App.HIS_Service.TrasenWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrasenWSSoapClient : System.ServiceModel.ClientBase<Ipedf.App.HIS_Service.TrasenWSSoap>, Ipedf.App.HIS_Service.TrasenWSSoap {
        
        public TrasenWSSoapClient() {
        }
        
        public TrasenWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrasenWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrasenWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrasenWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ExeWebService(string PostType, string PostString) {
            return base.Channel.ExeWebService(PostType, PostString);
        }
        
        public string GetXml(string PostType, string PostString) {
            return base.Channel.GetXml(PostType, PostString);
        }
    }
}
