//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace NFine.Web.FundSapInput {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZFI02WS_006", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZFI02WS_006 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Zfi02Fm006OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZFI02WS_006() {
            this.Url = global::NFine.Web.Properties.Settings.Default.NFine_Web_FundSapInput_ZFI02WS_006;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Zfi02Fm006CompletedEventHandler Zfi02Fm006Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZFI02WS_006:Zfi02Fm006Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zfi02Fm006Response", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zfi02Fm006Response Zfi02Fm006([System.Xml.Serialization.XmlElementAttribute("Zfi02Fm006", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zfi02Fm006 Zfi02Fm0061) {
            object[] results = this.Invoke("Zfi02Fm006", new object[] {
                        Zfi02Fm0061});
            return ((Zfi02Fm006Response)(results[0]));
        }
        
        /// <remarks/>
        public void Zfi02Fm006Async(Zfi02Fm006 Zfi02Fm0061) {
            this.Zfi02Fm006Async(Zfi02Fm0061, null);
        }
        
        /// <remarks/>
        public void Zfi02Fm006Async(Zfi02Fm006 Zfi02Fm0061, object userState) {
            if ((this.Zfi02Fm006OperationCompleted == null)) {
                this.Zfi02Fm006OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZfi02Fm006OperationCompleted);
            }
            this.InvokeAsync("Zfi02Fm006", new object[] {
                        Zfi02Fm0061}, this.Zfi02Fm006OperationCompleted, userState);
        }
        
        private void OnZfi02Fm006OperationCompleted(object arg) {
            if ((this.Zfi02Fm006Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zfi02Fm006Completed(this, new Zfi02Fm006CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zfi02Fm006 {
        
        private string iAufnrField;
        
        private string iBelnrField;
        
        private string iBukrsField;
        
        private string iDmbtrField;
        
        private string iFlagField;
        
        private string iGjahrField;
        
        private string iLbbmField;
        
        private string iLgortField;
        
        private string iMonatField;
        
        private string iQdateField;
        
        private string iSgtxtField;
        
        private string iStatusField;
        
        private string iWaersField;
        
        private string iWerksField;
        
        private string iZfiJfdmField;
        
        private string iZfiLyxhField;
        
        private string iZjpnoField;
        
        private Zfi02T011[] tJflyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IAufnr {
            get {
                return this.iAufnrField;
            }
            set {
                this.iAufnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IBelnr {
            get {
                return this.iBelnrField;
            }
            set {
                this.iBelnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IBukrs {
            get {
                return this.iBukrsField;
            }
            set {
                this.iBukrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDmbtr {
            get {
                return this.iDmbtrField;
            }
            set {
                this.iDmbtrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFlag {
            get {
                return this.iFlagField;
            }
            set {
                this.iFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IGjahr {
            get {
                return this.iGjahrField;
            }
            set {
                this.iGjahrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ILbbm {
            get {
                return this.iLbbmField;
            }
            set {
                this.iLbbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ILgort {
            get {
                return this.iLgortField;
            }
            set {
                this.iLgortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMonat {
            get {
                return this.iMonatField;
            }
            set {
                this.iMonatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IQdate {
            get {
                return this.iQdateField;
            }
            set {
                this.iQdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISgtxt {
            get {
                return this.iSgtxtField;
            }
            set {
                this.iSgtxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IStatus {
            get {
                return this.iStatusField;
            }
            set {
                this.iStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IWaers {
            get {
                return this.iWaersField;
            }
            set {
                this.iWaersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IWerks {
            get {
                return this.iWerksField;
            }
            set {
                this.iWerksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IZfiJfdm {
            get {
                return this.iZfiJfdmField;
            }
            set {
                this.iZfiJfdmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IZfiLyxh {
            get {
                return this.iZfiLyxhField;
            }
            set {
                this.iZfiLyxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IZjpno {
            get {
                return this.iZjpnoField;
            }
            set {
                this.iZjpnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zfi02T011[] TJfly {
            get {
                return this.tJflyField;
            }
            set {
                this.tJflyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zfi02T011 {
        
        private string mandtField;
        
        private string zfiLyxhField;
        
        private string bukrsField;
        
        private string gjahrField;
        
        private string monatField;
        
        private string qdateField;
        
        private string werksField;
        
        private string lgortField;
        
        private string zfiJfdmField;
        
        private string aufnrField;
        
        private decimal dmbtrField;
        
        private string waersField;
        
        private string zjpnoField;
        
        private string zmmLbbmField;
        
        private string bklasField;
        
        private string sgtxtField;
        
        private string belnrField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZfiLyxh {
            get {
                return this.zfiLyxhField;
            }
            set {
                this.zfiLyxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gjahr {
            get {
                return this.gjahrField;
            }
            set {
                this.gjahrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Monat {
            get {
                return this.monatField;
            }
            set {
                this.monatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qdate {
            get {
                return this.qdateField;
            }
            set {
                this.qdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZfiJfdm {
            get {
                return this.zfiJfdmField;
            }
            set {
                this.zfiJfdmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aufnr {
            get {
                return this.aufnrField;
            }
            set {
                this.aufnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Dmbtr {
            get {
                return this.dmbtrField;
            }
            set {
                this.dmbtrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zjpno {
            get {
                return this.zjpnoField;
            }
            set {
                this.zjpnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZmmLbbm {
            get {
                return this.zmmLbbmField;
            }
            set {
                this.zmmLbbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bklas {
            get {
                return this.bklasField;
            }
            set {
                this.bklasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sgtxt {
            get {
                return this.sgtxtField;
            }
            set {
                this.sgtxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Belnr {
            get {
                return this.belnrField;
            }
            set {
                this.belnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zfi02Fm006Response {
        
        private string oMsgtxField;
        
        private string oMsgtyField;
        
        private Zfi02T011[] tJflyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OMsgtx {
            get {
                return this.oMsgtxField;
            }
            set {
                this.oMsgtxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OMsgty {
            get {
                return this.oMsgtyField;
            }
            set {
                this.oMsgtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zfi02T011[] TJfly {
            get {
                return this.tJflyField;
            }
            set {
                this.tJflyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Zfi02Fm006CompletedEventHandler(object sender, Zfi02Fm006CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zfi02Fm006CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zfi02Fm006CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zfi02Fm006Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zfi02Fm006Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591