//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace NFine.Web.FundSap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWS_WWKF", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZWS_WWKF : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Zfi02FmWwkfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWS_WWKF() {
            this.Url = global::NFine.Web.Properties.Settings.Default.NFine_Web_FundSap_ZWS_WWKF;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Zfi02FmWwkfCompletedEventHandler Zfi02FmWwkfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_WWKF:Zfi02FmWwkfRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zfi02FmWwkfResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zfi02FmWwkfResponse Zfi02FmWwkf([System.Xml.Serialization.XmlElementAttribute("Zfi02FmWwkf", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zfi02FmWwkf Zfi02FmWwkf1) {
            object[] results = this.Invoke("Zfi02FmWwkf", new object[] {
                        Zfi02FmWwkf1});
            return ((Zfi02FmWwkfResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Zfi02FmWwkfAsync(Zfi02FmWwkf Zfi02FmWwkf1) {
            this.Zfi02FmWwkfAsync(Zfi02FmWwkf1, null);
        }
        
        /// <remarks/>
        public void Zfi02FmWwkfAsync(Zfi02FmWwkf Zfi02FmWwkf1, object userState) {
            if ((this.Zfi02FmWwkfOperationCompleted == null)) {
                this.Zfi02FmWwkfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZfi02FmWwkfOperationCompleted);
            }
            this.InvokeAsync("Zfi02FmWwkf", new object[] {
                        Zfi02FmWwkf1}, this.Zfi02FmWwkfOperationCompleted, userState);
        }
        
        private void OnZfi02FmWwkfOperationCompleted(object arg) {
            if ((this.Zfi02FmWwkfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zfi02FmWwkfCompleted(this, new Zfi02FmWwkfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zfi02FmWwkf {
        
        private string iCardidField;
        
        private string iLgortField;
        
        private string iPasswdField;
        
        private Zfi02S026[] tAufkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ICardid {
            get {
                return this.iCardidField;
            }
            set {
                this.iCardidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ILgort {
            get {
                return this.iLgortField;
            }
            set {
                this.iLgortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IPasswd {
            get {
                return this.iPasswdField;
            }
            set {
                this.iPasswdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zfi02S026[] TAufk {
            get {
                return this.tAufkField;
            }
            set {
                this.tAufkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zfi02S026 {
        
        private string cardidField;
        
        private string cardnoField;
        
        private string zjfidField;
        
        private string zjyfgField;
        
        private string zprmgField;
        
        private string ernamField;
        
        private string erdatField;
        
        private string aufnrField;
        
        private string zltextField;
        
        private decimal dmbtrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cardid {
            get {
                return this.cardidField;
            }
            set {
                this.cardidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cardno {
            get {
                return this.cardnoField;
            }
            set {
                this.cardnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zjfid {
            get {
                return this.zjfidField;
            }
            set {
                this.zjfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zjyfg {
            get {
                return this.zjyfgField;
            }
            set {
                this.zjyfgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zprmg {
            get {
                return this.zprmgField;
            }
            set {
                this.zprmgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ernam {
            get {
                return this.ernamField;
            }
            set {
                this.ernamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aufnr {
            get {
                return this.aufnrField;
            }
            set {
                this.aufnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zltext {
            get {
                return this.zltextField;
            }
            set {
                this.zltextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Dmbtr {
            get {
                return this.dmbtrField;
            }
            set {
                this.dmbtrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zbc00SMsg {
        
        private string zbcLogidField;
        
        private string msgtyField;
        
        private string zbcTnameField;
        
        private string zbcTbidxField;
        
        private string msgtxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZbcLogid {
            get {
                return this.zbcLogidField;
            }
            set {
                this.zbcLogidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgty {
            get {
                return this.msgtyField;
            }
            set {
                this.msgtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZbcTname {
            get {
                return this.zbcTnameField;
            }
            set {
                this.zbcTnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZbcTbidx {
            get {
                return this.zbcTbidxField;
            }
            set {
                this.zbcTbidxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgtx {
            get {
                return this.msgtxField;
            }
            set {
                this.msgtxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zfi02FmWwkfResponse {
        
        private Zbc00SMsg osMsgField;
        
        private Zfi02S026[] tAufkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zbc00SMsg OsMsg {
            get {
                return this.osMsgField;
            }
            set {
                this.osMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zfi02S026[] TAufk {
            get {
                return this.tAufkField;
            }
            set {
                this.tAufkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Zfi02FmWwkfCompletedEventHandler(object sender, Zfi02FmWwkfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zfi02FmWwkfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zfi02FmWwkfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zfi02FmWwkfResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zfi02FmWwkfResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591