//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace NFine.Web.HrmSap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZHRWS_KQJLMX", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZHRWS_KQJLMX : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Zhr00FmKqjlmxOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZHRWS_KQJLMX() {
            this.Url = global::NFine.Web.Properties.Settings.Default.NFine_Web_HrmSap_ZHRWS_KQJLMX;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Zhr00FmKqjlmxCompletedEventHandler Zhr00FmKqjlmxCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZHRWS_KQJLMX:Zhr00FmKqjlmxReques" +
            "t", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zhr00FmKqjlmxResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zhr00FmKqjlmxResponse Zhr00FmKqjlmx([System.Xml.Serialization.XmlElementAttribute("Zhr00FmKqjlmx", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zhr00FmKqjlmx Zhr00FmKqjlmx1) {
            object[] results = this.Invoke("Zhr00FmKqjlmx", new object[] {
                        Zhr00FmKqjlmx1});
            return ((Zhr00FmKqjlmxResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Zhr00FmKqjlmxAsync(Zhr00FmKqjlmx Zhr00FmKqjlmx1) {
            this.Zhr00FmKqjlmxAsync(Zhr00FmKqjlmx1, null);
        }
        
        /// <remarks/>
        public void Zhr00FmKqjlmxAsync(Zhr00FmKqjlmx Zhr00FmKqjlmx1, object userState) {
            if ((this.Zhr00FmKqjlmxOperationCompleted == null)) {
                this.Zhr00FmKqjlmxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZhr00FmKqjlmxOperationCompleted);
            }
            this.InvokeAsync("Zhr00FmKqjlmx", new object[] {
                        Zhr00FmKqjlmx1}, this.Zhr00FmKqjlmxOperationCompleted, userState);
        }
        
        private void OnZhr00FmKqjlmxOperationCompleted(object arg) {
            if ((this.Zhr00FmKqjlmxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zhr00FmKqjlmxCompleted(this, new Zhr00FmKqjlmxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmKqjlmx {
        
        private string begdaField;
        
        private string enddaField;
        
        private string guidField;
        
        private string nachnField;
        
        private string pernrField;
        
        private string senroField;
        
        private string zhrbzField;
        
        private string zhrjblxField;
        
        private string zhrjbzdField;
        
        private string zhrksField;
        
        private string zhrksmsField;
        
        private string zhrqjlxField;
        
        private string zhrqjmsField;
        
        private string zhrzkField;
        
        private string zhrzkmsField;
        
        private string zhrzyksField;
        
        private int zqjtsField;
        
        private string ztjrField;
        
        private string ztjrqField;
        
        private System.DateTime ztjsjField;
        
        private bool ztjsjFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Begda {
            get {
                return this.begdaField;
            }
            set {
                this.begdaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Endda {
            get {
                return this.enddaField;
            }
            set {
                this.enddaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nachn {
            get {
                return this.nachnField;
            }
            set {
                this.nachnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Senro {
            get {
                return this.senroField;
            }
            set {
                this.senroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrbz {
            get {
                return this.zhrbzField;
            }
            set {
                this.zhrbzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrjblx {
            get {
                return this.zhrjblxField;
            }
            set {
                this.zhrjblxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrjbzd {
            get {
                return this.zhrjbzdField;
            }
            set {
                this.zhrjbzdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrks {
            get {
                return this.zhrksField;
            }
            set {
                this.zhrksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrksms {
            get {
                return this.zhrksmsField;
            }
            set {
                this.zhrksmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrqjlx {
            get {
                return this.zhrqjlxField;
            }
            set {
                this.zhrqjlxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrqjms {
            get {
                return this.zhrqjmsField;
            }
            set {
                this.zhrqjmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrzk {
            get {
                return this.zhrzkField;
            }
            set {
                this.zhrzkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrzkms {
            get {
                return this.zhrzkmsField;
            }
            set {
                this.zhrzkmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrzyks {
            get {
                return this.zhrzyksField;
            }
            set {
                this.zhrzyksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Zqjts {
            get {
                return this.zqjtsField;
            }
            set {
                this.zqjtsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ztjr {
            get {
                return this.ztjrField;
            }
            set {
                this.ztjrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ztjrq {
            get {
                return this.ztjrqField;
            }
            set {
                this.ztjrqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time")]
        public System.DateTime Ztjsj {
            get {
                return this.ztjsjField;
            }
            set {
                this.ztjsjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZtjsjSpecified {
            get {
                return this.ztjsjFieldSpecified;
            }
            set {
                this.ztjsjFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmKqjlmxResponse {
        
        private string mesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Zhr00FmKqjlmxCompletedEventHandler(object sender, Zhr00FmKqjlmxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zhr00FmKqjlmxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zhr00FmKqjlmxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zhr00FmKqjlmxResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zhr00FmKqjlmxResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591