//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.ChangeStatus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZHRWS_PSHX", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZHRWS_PSHX : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Zhr00FmZcpshxztOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZHRWS_PSHX() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_WebReference_ZHRWS_PSHX;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Zhr00FmZcpshxztCompletedEventHandler Zhr00FmZcpshxztCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZHRWS_PSHX:Zhr00FmZcpshxztReques" +
            "t", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zhr00FmZcpshxztResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zhr00FmZcpshxztResponse Zhr00FmZcpshxzt([System.Xml.Serialization.XmlElementAttribute("Zhr00FmZcpshxzt", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zhr00FmZcpshxzt Zhr00FmZcpshxzt1) {
            object[] results = this.Invoke("Zhr00FmZcpshxzt", new object[] {
                        Zhr00FmZcpshxzt1});
            return ((Zhr00FmZcpshxztResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Zhr00FmZcpshxztAsync(Zhr00FmZcpshxzt Zhr00FmZcpshxzt1) {
            this.Zhr00FmZcpshxztAsync(Zhr00FmZcpshxzt1, null);
        }
        
        /// <remarks/>
        public void Zhr00FmZcpshxztAsync(Zhr00FmZcpshxzt Zhr00FmZcpshxzt1, object userState) {
            if ((this.Zhr00FmZcpshxztOperationCompleted == null)) {
                this.Zhr00FmZcpshxztOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZhr00FmZcpshxztOperationCompleted);
            }
            this.InvokeAsync("Zhr00FmZcpshxzt", new object[] {
                        Zhr00FmZcpshxzt1}, this.Zhr00FmZcpshxztOperationCompleted, userState);
        }
        
        private void OnZhr00FmZcpshxztOperationCompleted(object arg) {
            if ((this.Zhr00FmZcpshxztCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zhr00FmZcpshxztCompleted(this, new Zhr00FmZcpshxztCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmZcpshxzt {
        
        private string icnumField;
        
        private string zhrzjlxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Icnum {
            get {
                return this.icnumField;
            }
            set {
                this.icnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zhrzjlx {
            get {
                return this.zhrzjlxField;
            }
            set {
                this.zhrzjlxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmZcpshxztResponse {
        
        private string mesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Zhr00FmZcpshxztCompletedEventHandler(object sender, Zhr00FmZcpshxztCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zhr00FmZcpshxztCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zhr00FmZcpshxztCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zhr00FmZcpshxztResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zhr00FmZcpshxztResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591