//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipedf.Web {
    
    
    public partial class PageObject_BGT_B_DEPT_FUND_EXE {
        
        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// navigator 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComPageNavigator navigator;
        
        /// <summary>
        /// command 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComControlBar command;
        
        /// <summary>
        /// lblState 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblState;
        
        /// <summary>
        /// btnDelete 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComButton btnDelete;
        
        /// <summary>
        /// resultPannel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl resultPannel;
        
        /// <summary>
        /// gvList 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComGridView gvList;
        
        /// <summary>
        /// pager 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComPager pager;
        
        /// <summary>
        /// editPannel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl editPannel;
        
        /// <summary>
        /// ddlInputBUDGET_YEAR 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComBaseBox ddlInputBUDGET_YEAR;
        
        /// <summary>
        /// ddlInputBUDGET_DEPT_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComBaseBox ddlInputBUDGET_DEPT_ID;
        
        /// <summary>
        /// ddlInputBGT_D_BUDGET_ITEM_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComBaseBox ddlInputBGT_D_BUDGET_ITEM_ID;
        
        /// <summary>
        /// txtInputFREE_FIELD3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputFREE_FIELD3;
        
        /// <summary>
        /// txtInputNEW_FUND_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputNEW_FUND_MONEY;
        
        /// <summary>
        /// revtxtInputNEW_FUND_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtInputNEW_FUND_MONEY;
        
        /// <summary>
        /// txtInputFREE_FIELD 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputFREE_FIELD;
        
        /// <summary>
        /// txtInputDECALRE_CAUSE 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputDECALRE_CAUSE;
        
        /// <summary>
        /// txtInputNAME 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputNAME;
        
        /// <summary>
        /// txtInputCONTROL_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputCONTROL_MONEY;
        
        /// <summary>
        /// revtxtInputCONTROL_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtInputCONTROL_MONEY;
        
        /// <summary>
        /// ddlInputIS_FIXED 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComDropDownList ddlInputIS_FIXED;
        
        /// <summary>
        /// txtInputFREE_FIELD2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputFREE_FIELD2;
        
        /// <summary>
        /// ddlInputFUND_TYPE_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComBaseBox ddlInputFUND_TYPE_ID;
        
        /// <summary>
        /// txtInputREF_TAB_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputREF_TAB_ID;
        
        /// <summary>
        /// ddlInputIS_UPDATE_ITEM 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComDropDownList ddlInputIS_UPDATE_ITEM;
        
        /// <summary>
        /// txtInputFUND_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputFUND_MONEY;
        
        /// <summary>
        /// revtxtInputFUND_MONEY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revtxtInputFUND_MONEY;
        
        /// <summary>
        /// txtInputFINANCE_IDEA 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputFINANCE_IDEA;
        
        /// <summary>
        /// ddlInputIS_PERFORMANCE 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComDropDownList ddlInputIS_PERFORMANCE;
        
        /// <summary>
        /// txtInputITEM_NAME 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputITEM_NAME;
        
        /// <summary>
        /// ddlInputDEPT_USER_ID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComBaseBox ddlInputDEPT_USER_ID;
        
        /// <summary>
        /// txtInputCODE 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Ipedf.Web.Control.ComTextBox txtInputCODE;
    }
}
