//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace XH_Print.Srzm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZHR00_CW2", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZHR00_CW2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Zhr00FmSrzmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZHR00_CW2() {
            this.Url = global::XH_Print.Properties.Settings.Default.XH_Print_Srzm_ZHR00_CW2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Zhr00FmSrzmCompletedEventHandler Zhr00FmSrzmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZHR00_CW2:Zhr00FmSrzmRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zhr00FmSrzmResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zhr00FmSrzmResponse Zhr00FmSrzm([System.Xml.Serialization.XmlElementAttribute("Zhr00FmSrzm", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zhr00FmSrzm Zhr00FmSrzm1) {
            object[] results = this.Invoke("Zhr00FmSrzm", new object[] {
                        Zhr00FmSrzm1});
            return ((Zhr00FmSrzmResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Zhr00FmSrzmAsync(Zhr00FmSrzm Zhr00FmSrzm1) {
            this.Zhr00FmSrzmAsync(Zhr00FmSrzm1, null);
        }
        
        /// <remarks/>
        public void Zhr00FmSrzmAsync(Zhr00FmSrzm Zhr00FmSrzm1, object userState) {
            if ((this.Zhr00FmSrzmOperationCompleted == null)) {
                this.Zhr00FmSrzmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZhr00FmSrzmOperationCompleted);
            }
            this.InvokeAsync("Zhr00FmSrzm", new object[] {
                        Zhr00FmSrzm1}, this.Zhr00FmSrzmOperationCompleted, userState);
        }
        
        private void OnZhr00FmSrzmOperationCompleted(object arg) {
            if ((this.Zhr00FmSrzmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zhr00FmSrzmCompleted(this, new Zhr00FmSrzmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmSrzm {
        
        private string icnumField;
        
        private string ipField;
        
        private string zdtmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Icnum {
            get {
                return this.icnumField;
            }
            set {
                this.icnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zdtm {
            get {
                return this.zdtmField;
            }
            set {
                this.zdtmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr00FmSrzmResponse {
        
        private string icnumField;
        
        private string mesField;
        
        private string nachnField;
        
        private string shnsrdxField;
        
        private string shnsrxxField;
        
        private string shysrdxField;
        
        private string shysrxxField;
        
        private string sqnsrdxField;
        
        private string sqnsrxxField;
        
        private string sqysrdxField;
        
        private string sqysrxxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Icnum {
            get {
                return this.icnumField;
            }
            set {
                this.icnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nachn {
            get {
                return this.nachnField;
            }
            set {
                this.nachnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shnsrdx {
            get {
                return this.shnsrdxField;
            }
            set {
                this.shnsrdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shnsrxx {
            get {
                return this.shnsrxxField;
            }
            set {
                this.shnsrxxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shysrdx {
            get {
                return this.shysrdxField;
            }
            set {
                this.shysrdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shysrxx {
            get {
                return this.shysrxxField;
            }
            set {
                this.shysrxxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sqnsrdx {
            get {
                return this.sqnsrdxField;
            }
            set {
                this.sqnsrdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sqnsrxx {
            get {
                return this.sqnsrxxField;
            }
            set {
                this.sqnsrxxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sqysrdx {
            get {
                return this.sqysrdxField;
            }
            set {
                this.sqysrdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sqysrxx {
            get {
                return this.sqysrxxField;
            }
            set {
                this.sqysrxxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Zhr00FmSrzmCompletedEventHandler(object sender, Zhr00FmSrzmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zhr00FmSrzmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zhr00FmSrzmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zhr00FmSrzmResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zhr00FmSrzmResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591